spring: 
  datasource: 
     url: jdbc:mysql://localhost:3306/oauth
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
     hibernate:
        ddl-auto: update
     show-sql: false
     
security: 
   oauth2:
     resource:
       filter-order: 3
       
ldap: 
    url: ldap://localhost:10389/
    dn: ou=users,dc=example,dc=com
    
client: 
    id: techmango-client 
    secret: techmango
    
server:
  port: 8081
  
default:
    mail:
       to: sofia@techmango.net
       flag: yes

otp:
  length: 6 