spring:
  datasource: 
     url: jdbc:mysql://localhost:3306/failedevents
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     hibernate:
        ddl-auto: update
     show-sql: false
  kafka:
    bootstrap-servers: localhost:9092

app:
   topic:
      topic: event
      
server: 
   port: 8084